"""
Pandera schemas for validating dataframes throughout the MRD pipeline.

This module defines the expected structure, data types, and constraints for
the pandas DataFrames that are passed between different stages of the pipeline.
Using these schemas helps to catch data integrity issues early and makes the
pipeline more robust and easier to debug.
"""

import pandera as pa
from pandera.typing import DataFrame, Series

class SimulatedReadsSchema(pa.DataFrameModel):
    """
    Schema for the DataFrame generated by the `simulate_reads` stage.
    """
    umi: Series[str] = pa.Field(description="Unique Molecular Identifier for a read group.")
    allele: Series[str] = pa.Field(description="The genetic allele ('A', 'B', 'C', etc.).")
    is_variant: Series[bool] = pa.Field(description="True if the read represents the variant allele.")
    has_error: Series[bool] = pa.Field(description="True if a sequencing error was introduced.")
    
    class Config:
        strict = "filter"  # Allow other columns but only validate these
        coerce = True

class CollapsedUMIsSchema(pa.DataFrameModel):
    """
    Schema for the DataFrame after UMI consensus/collapsing.
    """
    umi_sequence: Series[str] = pa.Field(description="The consensus sequence of the UMI.")
    total_reads: Series[int] = pa.Field(ge=1, description="Total number of raw reads for this UMI.")
    variant_reads: Series[int] = pa.Field(ge=0, description="Number of reads supporting the variant allele.")
    umi_fraction: Series[float] = pa.Field(ge=0.0, le=1.0, description="Fraction of variant reads in the UMI group.")
    is_true_variant: Series[bool] = pa.Field(description="Ground truth: True if the UMI corresponds to a true variant.")
    
    class Config:
        strict = "filter"
        coerce = True

class ErrorModelSchema(pa.DataFrameModel):
    """
    Schema for the DataFrame containing the fitted error model.
    """
    umi_fraction: Series[float] = pa.Field(ge=0.0, le=1.0, description="Binned UMI fraction.")
    error_rate: Series[float] = pa.Field(ge=0.0, le=1.0, description="Calculated error rate for the bin.")

    class Config:
        strict = "filter"
        coerce = True

class MRDCallsSchema(CollapsedUMIsSchema):
    """
    Schema for the final DataFrame with MRD calls. 
    Extends CollapsedUMIsSchema with prediction columns.
    """
    predicted_is_variant: Series[bool] = pa.Field(description="The model's prediction of whether the UMI is a variant.")
    prediction_prob: Series[float] = pa.Field(ge=0.0, le=1.0, nullable=True, description="The probability score from the classification model.")
    
    class Config:
        strict = "filter"
        coerce = True

# --- Type hints for use in function signatures ---
SimulatedReadsDF = DataFrame[SimulatedReadsSchema]
CollapsedUMIsDF = DataFrame[CollapsedUMIsSchema]
ErrorModelDF = DataFrame[ErrorModelSchema]
MRDCallsDF = DataFrame[MRDCallsSchema]
